In [2]:
import numpy as np

In [3]:
a = np.array([1,3,4,5,23])
b = np.array([3,2,33,5,2])
c = np.array([5,6,7,5,6,12])

In [4]:
a+b

array([ 4,  5, 37, 10, 25])

In [5]:
a-c #This is because the both the arrays must be of same shape.

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [6]:
b*a

array([  3,   6, 132,  25,  46])

In [7]:
a/b

array([ 0.33333333,  1.5       ,  0.12121212,  1.        , 11.5       ])

In [8]:
scalarValue = 2
normalList = [12,45,32,55,11]
print(normalList)

[12, 45, 32, 55, 11]


In [9]:
scalarValue*normalList
# If vector is declared as normal array, then instead of scalar value multiplied by each element of array,
# It multiples the list size and duplicates the value by scalar value times(In this case its 2 times is duplicated)
# Hence we go to numpy arrays.

[12, 45, 32, 55, 11, 12, 45, 32, 55, 11]

In [10]:
list_into_np_array = np.array(normalList)
print(list_into_np_array)

[12 45 32 55 11]


In [11]:
scalarValue*list_into_np_array

array([ 24,  90,  64, 110,  22])

In [12]:
columnVector = np.array([ [1,2],[34],[5]]) #Can give only one value inside the square brackets, else its matrix.
print(columnVector)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [13]:
# Demo of Dot product in vector.
np.dot(a,b)

212

In [14]:
# Distributive property of Dot product
# a.(b+c) = a.b + a.c 

#LHS 
x = np.array([1,2,3,4,8])
y = np.array([5,8,7,9,6])
z = np.array([2,4,8,6,10])

np.dot(x,y+z)

264

In [15]:
#RHS
print(np.dot(x,y)+np.dot(x,z))

264


In [16]:
#To find Magnitude

from numpy import linalg as lng

lng.norm(z)

14.832396974191326

In [17]:
# Vector Projection of x onto y is given by

vectorProjection = (np.dot(x,y)/np.dot(y,y))*y
print(vectorProjection)

[2.47058824 3.95294118 3.45882353 4.44705882 2.96470588]


In [25]:
# To Solve Linear Equation using Inversion method

A = np.array([[1,2],[3,4]]) # A being the linear equations.
B = np.array([5,11]) # B being the constant matrix.

# A inverse . B = [x,y]

Ainverse = np.linalg.inv(A)

x = np.dot(Ainverse,B)
print("The x and y values are: "+str(x))

#Checking the values are correct by A.x = B

print("The value of B is : ",str(np.dot(A,x)))

The x and y values are: [1. 2.]
The value of B is :  [ 5. 11.]


In [26]:
#To find the determinant of A 

det = np.linalg.det(A)
det

-2.0000000000000004